### ISSUE TITLE
Use docker bridge networking mode

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-deploy#3]
the current docker configuration in [docker-compose.yml](https://github.com/cta-wave/dpctf-deploy/blob/master/docker-compose.yml) uses `host` networking mode. 

```yaml
services:
  dpctf:
    container_name: dpctf
    image: dpctf:0.0.0
    restart: always
    #ports:
      #- "8000:8000"
    network_mode: "host"
```
on Mac, the `bridge` networking mode (which is the default docker networking mode) works better but the port mapping needs to be configured:

```yaml
services:
  dpctf:
    container_name: dpctf
    image: dpctf:0.0.0
    restart: always
    ports:
      - "8000:8000"
    network_mode: "bridge"
```

@yanj-github can you test the `bridge` mode if it works fine on your side. If it works for you, we will use `bridge` networking mode as default.
